'use client';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowUpRight, ArrowDown, ArrowRight, Check, Mail, Clock3, ChevronLeft, Rewind, Sparkles, Globe2, Workflow, Layers3, Plus, Minus, Play } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';

const services = [
 {id:'ai',number:'01',name:'The AI lab',title:'AI that actually\nhas a job to do.',copy:'A helpful first response. The right questions. An enquiry ready for you to act on. Build AI agents that capture leads, answer questions and support your customers.',cta:'Explore AI agents',detail:['Website assistants that answer from your business information','Lead capture and useful qualification questions','Customer enquiry and information assistants','Clear handover to a person when it matters'],outcome:'More useful conversations. Fewer enquiries left waiting.'},
 {id:'automation',number:'02',name:'The automation lab',title:'Do it repeatedly?\nLet’s talk.',copy:'The copying, chasing, reminding and checking. Connect those everyday tasks into a workflow that keeps moving while you get on with the work.',cta:'Explore automation',detail:['Quote and enquiry follow-up','Appointment reminders and customer updates','Internal notifications and task handovers','Moving information between the tools you already use'],outcome:'Less repetitive admin. More time for the work that needs you.'},
 {id:'websites',number:'03',name:'The web lab',title:'Your website\nshouldn’t just sit there.',copy:'Give your next customer a clear way in. We build business websites and digital experiences that turn interest into enquiries and connect to the rest of your business.',cta:'Explore websites',detail:['Business websites and focused landing pages','Clear enquiry journeys and lead capture','Interactive digital experiences','Website connections to your CRM and workflows'],outcome:'A website that plays an active part in your business.'},
 {id:'integrations',number:'04',name:'The integration lab',title:'Make your systems\ntalk to each other.',copy:'One enquiry shouldn’t mean entering the same details five times. Bring your leads, customer information and everyday tools together.',cta:'Explore integrations',detail:['CRM setup and organised lead pipelines','Connections between your existing software','Automatic lead updates and follow-up triggers','Custom integrations built around your workflow'],outcome:'Organised leads. Fewer gaps between tools.'},
];
const problems=[['I’m missing enquiries',['AI lead agent','Lead capture','CRM','Automated follow-up']],['I spend too much time on admin',['Workflow review','Task automation','Connected tools']],['My website isn’t generating leads',['Website review','Enquiry journey','Lead capture']],['I’m bad at following up',['Lead pipeline','Useful reminders','Automated follow-up']],['My systems don’t talk to each other',['Integration review','Connected data','Shared workflows']],['I’m not sure yet',['A conversation','Find the friction','A practical starting point']]] as const;
const experiments=['AI lead generation agent','Automated quote follow-up','Tradie lead management','Interactive business website','Customer follow-up automation','CRM pipeline automation'];
const stages=['Website','AI lead agent','Qualification','CRM','Automation'];
function Chapter({n,children}:{n:string,children:React.ReactNode}){return <div className="eyebrow"><span className="chapter-number">{n}</span>{children}</div>;}
function QuoteLink({children='Get a quote',light=false}:{children?:React.ReactNode,light?:boolean}){return <a className={`action ${light?'action-light':''}`} href="#quote">{children}<ArrowUpRight size={18}/></a>;}
function Lead({className=''}:{className?:string}){return <div className={`lead ${className}`} aria-label="Sarah’s enquiry"><Mail size={23}/><span>S</span></div>;}

export default function Story(){
 const root=useRef<HTMLDivElement>(null);const [revealed,setRevealed]=useState(false);const [service,setService]=useState<number|null>(null);const [experiment,setExperiment]=useState<number|null>(null);const [demoStage,setDemoStage]=useState(0);const [demoName,setDemoName]=useState('Sarah');const [demoService,setDemoService]=useState('Switchboard replacement');const [problem,setProblem]=useState<number|null>(null);const [legal,setLegal]=useState<'privacy'|'terms'|'about'|null>(null);
 useEffect(()=>{const node=document.getElementById('rewind');const onScroll=()=>{if(node)setRevealed(node.getBoundingClientRect().top<140);};onScroll();window.addEventListener('scroll',onScroll,{passive:true});let cleanup=()=>{};let cancelled=false;let motionLoaded=false;const media=window.matchMedia('(min-width: 900px) and (min-height: 700px) and (prefers-reduced-motion: no-preference)');const loadMotion=async()=>{if(motionLoaded||!media.matches)return;motionLoaded=true;const {gsap}=await import('gsap');const {ScrollTrigger}=await import('gsap/ScrollTrigger');if(cancelled)return;gsap.registerPlugin(ScrollTrigger);const mm=gsap.matchMedia();mm.add('(min-width: 900px) and (min-height: 700px) and (prefers-reduced-motion: no-preference)',()=>{const ctx=gsap.context(()=>{
 gsap.to('.opening-image',{scale:1.07,yPercent:3,ease:'none',scrollTrigger:{trigger:'.opening',start:'top top',end:'bottom top',scrub:1}});
 gsap.fromTo('.incoming',{y:70,opacity:0},{y:0,opacity:1,scrollTrigger:{trigger:'.opening',start:'top+=30 top',end:'bottom 90%',scrub:1}});
 gsap.to('.lost-lead',{x:260,y:180,rotation:32,opacity:0,ease:'power1.in',scrollTrigger:{trigger:'.missed',start:'30% center',end:'bottom center',scrub:1}});
 gsap.from('.task-slip',{x:80,opacity:0,stagger:.22,scrollTrigger:{trigger:'.missed',start:'top 70%',end:'50% 50%',scrub:1}});
 const clock={v:666};gsap.to(clock,{v:642,ease:'none',onUpdate:()=>{const el=document.querySelector('.rewind-clock');if(el)el.textContent=`${Math.floor(clock.v/60)}:${String(Math.floor(clock.v%60)).padStart(2,'0')}`;},scrollTrigger:{trigger:'.rewind',start:'top 75%',end:'65% center',scrub:1}});
 gsap.fromTo('.rewind-lead',{x:220,y:80,rotation:25},{x:0,y:0,rotation:0,scrollTrigger:{trigger:'.rewind',start:'top 70%',end:'65% center',scrub:1}});
 const tl=gsap.timeline({scrollTrigger:{trigger:'.system-track',start:'top top',end:'+=1150',pin:'.system-stage',scrub:1,anticipatePin:1}});tl.from('.system-node',{y:65,opacity:0,stagger:.5}).from('.system-machine',{clipPath:'inset(0 100% 0 0)',duration:3},0).fromTo('.system-traveller',{left:'5%',opacity:0},{left:'88%',opacity:1,duration:3},.5);
 gsap.from('.journey>li',{y:35,opacity:.3,stagger:.3,scrollTrigger:{trigger:'.journey',start:'top 85%',end:'bottom 70%',scrub:1}});
 gsap.fromTo('.ending>img',{scale:1.06,x:-30},{scale:1,x:0,scrollTrigger:{trigger:'.ending',start:'top bottom',end:'bottom center',scrub:1}});
 gsap.from('.lab-overview-image',{scale:1.3,scrollTrigger:{trigger:'.zoom-out',start:'top bottom',end:'center center',scrub:1}});
 gsap.utils.toArray<HTMLElement>('.lab-room').forEach(el=>{gsap.from(el.querySelector('.lab-art'),{y:60,rotation:2,scrollTrigger:{trigger:el,start:'top 85%',end:'center center',scrub:1}});});
 },root);return ()=>{ctx.revert();const el=document.querySelector('.rewind-clock');if(el)el.textContent='10:42';};});cleanup=()=>mm.revert();};const onMedia=()=>{void loadMotion().catch(()=>{});};onMedia();media.addEventListener('change',onMedia);return()=>{cancelled=true;cleanup();media.removeEventListener('change',onMedia);window.removeEventListener('scroll',onScroll);};},[]);
 return <div ref={root}><a className="skip-link" href="#lab">Skip to the lab</a><header className={`site-header ${revealed?'brand-revealed':''}`}><a href="#start" className="wordmark" aria-label="Back to the beginning">{revealed?<><span className="brand-symbol">s.</span>SQUIRREL LABS</>:<><span className="story-mark">SL / 001</span><span className="header-story">A SMALL BUSINESS STORY</span></>}</a><nav aria-label="Main navigation"><a className="nav-lab" href="#lab">Explore the lab</a><QuoteLink/></nav></header><main>
 <section className="opening" id="start" aria-labelledby="story-title"><img className="opening-image" src="/images/workshop.webp" srcSet="/images/workshop-small.webp 800w, /images/workshop.webp 1600w" sizes="(max-width: 767px) 100vw, 100vw" alt="An electrician at work in a warm workshop, with tools and a van nearby" width="1536" height="1024" fetchPriority="high"/><div className="opening-shade"/><div className="opening-copy"><Chapter n="01">The workday</Chapter><p className="story-kicker">THE LEAD THAT ALMOST GOT AWAY</p><h1 id="story-title">Your next <br/>customer is <br/>already <em>looking <br/>for you.</em></h1><p>You’re doing what you do best.<br/>Somewhere, someone needs exactly that.</p></div><div className="incoming"><div className="message-icon"><Mail size={19}/></div><div><div className="message-meta">NEW ENQUIRY <span>10:42 AM</span></div><strong>Sarah</strong><p>Hi, could I get a quote for a<br className="desktop-break"/> switchboard replacement?</p></div><span className="unread-dot"/></div><div className="opening-bottom"><a href="#missed" className="scroll-cue"><span className="scroll-circle"><ArrowDown size={19}/></span>Scroll to follow the enquiry</a><span className="scene-caption">ONE ENQUIRY. TWO VERSIONS OF THE SAME DAY.</span><span className="scene-count">01 — 11</span></div></section>
 <section className="missed section-pad" id="missed"><div className="missed-copy"><Chapter n="02">The missed opportunity</Chapter><h2>You were busy<br/>doing <em>the work.</em></h2><p className="large-copy">The customer was still waiting.</p><p>A quote to finish. An email to answer. Another job to get to. You can’t be everywhere at once.</p><div className="waiting-clock"><Clock3 size={19}/>11:06 AM<span>Still unanswered</span></div></div><div className="paperwork"><div className="task-slip slip-one"><span>10:47 AM</span><strong>Quote #104 needs a follow-up</strong><small>Another thing for later.</small></div><div className="task-slip slip-two"><span>10:58 AM</span><strong>You have 6 unread emails</strong><small>And the work hasn’t stopped.</small></div><div className="task-slip slip-three"><span>SARAH · 11:06 AM</span><strong>Thanks, I’ve found someone.</strong><small>Enquiry closed</small></div><Lead className="lost-lead"/></div><p className="lost-statement">And just like that…<br/><strong>the opportunity is gone.</strong></p></section>
 <section className="rewind section-pad" id="rewind"><Chapter n="03">A second chance</Chapter><div className="rewind-top"><span><Rewind size={17}/>LET’S WIND THAT BACK</span><span className="rewind-clock" aria-label="Time returns to 10:42 AM">10:42</span><span>AM</span></div><div className="rewind-layout"><div><h2>There’s a<br/><em>better way.</em></h2><p>Same business. Same busy day.<br/>A little help behind the scenes.</p><div className="brand-introduction"><span className="brand-symbol">s.</span><span>SQUIRREL LABS<small>LET’S TRY THAT AGAIN.</small></span></div></div><div className="mascot-reveal"><img src="/images/squirrel.webp" srcSet="/images/squirrel-small.webp 800w, /images/squirrel.webp 1600w" sizes="(max-width: 767px) 100vw, 100vw" alt="The Squirrel Labs engineer connects a purple cable" width="1536" height="1024" loading="lazy"/><Lead className="rewind-lead"/><span className="annotation">let’s connect the dots.</span></div></div></section>
 <section className="system-track" id="system"><div className="system-stage section-pad"><Chapter n="04">Building the system</Chapter><div className="system-heading"><h2>A few connections.<br/><em>A big difference.</em></h2><p>A useful website. A helpful first response.<br/>The right information, in the right place.</p></div><div className="system"><div className="system-machine"><img src="/images/machine.webp" srcSet="/images/machine-small.webp 800w, /images/machine.webp 1600w" sizes="90vw" width="2137" height="736" alt="Five tactile workshop stations physically connected by purple pipes and brass couplings" loading="lazy"/></div><div className="system-connection"/><Lead className="system-traveller"/>{stages.map((s,i)=><div className="system-node" key={s}><span className="node-number">0{i+1}</span><div className="node-icon">{i===0?<Globe2/>:i===1?<Sparkles/>:i===2?<Check/>:i===3?<Layers3/>:<Workflow/>}</div><h3>{s}</h3><p>{['A clear way in','A helpful reply','The useful details','One organised place','Keep things moving'][i]}</p></div>)}</div><p className="system-note">Built around your business. Connected to the way you work.</p></div></section>
 <section className="replay section-pad" id="same-lead"><div className="replay-intro"><Chapter n="05">The same lead</Chapter><h2>This time,<br/>Sarah gets<br/><em>somewhere.</em></h2><p>The enquiry is the same.<br/>What happens next isn’t.</p><small className="demo-label">ILLUSTRATIVE JOURNEY · NOT A RESPONSE-TIME GUARANTEE</small></div><ol className="journey"><li><span className="journey-time">10:42 AM</span><div><h3>“Could I get a quote?”</h3><p>Sarah visits the website. The lead assistant replies and asks a few useful questions.</p><div className="qualification">{['Service','Location','Contact','Job details'].map(x=><span key={x}>{x}<Check size={13}/></span>)}</div></div></li><li><span className="journey-time">10:43 AM</span><div><h3>Everything in the right place.</h3><p>Her details enter the CRM. Sarah receives confirmation. The owner gets one useful notification.</p><div className="qualified-lead"><span className="qualified-title"><Check size={14}/>NEW QUALIFIED LEAD</span><div className="sarah-avatar">S</div><strong>Sarah</strong><p>Switchboard replacement<br/>Richmond VIC</p><span className="status-pill">Ready for callback</span></div></div></li><li><span className="journey-time">WHEN YOU’RE FREE</span><div><h3>A conversation. A customer.</h3><p>The owner calls Sarah when the job is finished. They agree on the work and book it in.</p><span className="booked"><Check size={17}/>Job booked</span></div></li></ol><div className="same-business">Same business.<br/><em>Better system.</em></div></section>
 <section className="zoom-out" id="overview"><div className="overview-copy section-pad"><Chapter n="06">The bigger picture</Chapter><h2>We build the systems<br/>behind <em>growing businesses.</em></h2><p>That was one enquiry. Imagine what else could work better.</p></div><div className="lab-panorama"><img className="lab-overview-image" src="/images/laboratory.webp" srcSet="/images/laboratory-small.webp 800w, /images/laboratory.webp 1600w" sizes="(max-width: 767px) 100vw, 100vw" alt="A connected miniature laboratory with purple machines moving amber enquiries into organised trays" width="1536" height="1024" loading="lazy"/><div className="panorama-labels"><span>WEBSITES</span><span>AI AGENTS</span><span>AUTOMATION</span><span>CRM & INTEGRATIONS</span></div></div></section>
 <section className="lab section-pad" id="lab"><Chapter n="07">Explore the lab</Chapter><div className="lab-title"><h2>Welcome<br/>to <em>the lab.</em></h2><p>Practical technology.<br/>Built to pull its weight.</p></div>{services.map((s,i)=><article className={`lab-room room-${i}`} id={s.id} key={s.id}><div className="lab-art"><img src={i===0||i===3?'/images/squirrel.webp':'/images/laboratory.webp'} srcSet={i===0||i===3?'/images/squirrel-small.webp 800w, /images/squirrel.webp 1600w':'/images/laboratory-small.webp 800w, /images/laboratory.webp 1600w'} sizes="(min-width:900px) 45vw, (min-width:600px) 40vw, 100vw" alt={i===0?'Our squirrel engineer connecting a customer enquiry system':i===3?'Connecting separate business tools':'A working miniature automation laboratory'} width="1536" height="1024" loading="lazy"/><span className="bench-label">WORKBENCH {s.number} / {s.name.toUpperCase()}</span><div className="art-label">{i===0?<Sparkles size={16}/>:i===1?<Check size={16}/>:i===2?<Globe2 size={16}/>:<Layers3 size={16}/>} {['How can I help you today?','Follow-up sent. Next task?','A new enquiry starts here.','Everyone on the same page.'][i]}</div></div><div className="lab-room-copy"><span className="eyebrow">{s.number} / {s.name}</span><h3>{s.title}</h3><p>{s.copy}</p><Button variant="ghost" className="text-link" onClick={()=>setService(i)}>{s.cta}<ArrowUpRight size={17}/></Button></div></article>)}</section>
 <section className="experiments section-pad" id="experiments"><Chapter n="08">Inside the lab</Chapter><div className="experiments-heading"><h2>Curiosity,<br/><em>put to work.</em></h2><div><p>See what we’re building.</p><small>Working ideas and interactive prototypes.<br/>No invented case studies. Just things to try.</small></div></div><div className="experiment-list">{experiments.map((x,i)=><button key={x} className="experiment-row" onClick={()=>{setExperiment(i);setDemoStage(0);}}><span className="experiment-number">EXP. 00{i+1}</span><span className="experiment-name">{x}</span><span className="prototype-tag">PROTOTYPE</span><ArrowUpRight size={22}/></button>)}</div></section>
 <section className="diagnosis section-pad" id="your-business"><div className="fourth-wall"><Chapter n="09">Over to you</Chapter><h2>Okay. Enough<br/>about <em>our lab.</em></h2><p>Let’s look at your business.</p><img src="/images/visitor.webp" srcSet="/images/visitor-small.webp 800w, /images/visitor.webp 1600w" sizes="(max-width:767px) 230px,390px" alt="The squirrel engineer turns toward you, ready to listen" width="1024" height="1536" loading="lazy"/></div><div className="problem-picker"><h3>What’s slowing you down?</h3><p>Pick the thing that sounds most familiar.</p><div className="problem-options">{problems.map(([label],i)=><Button variant="outline" key={label} aria-pressed={problem===i} className={`problem-option ${problem===i?'selected':''}`} onClick={()=>setProblem(i)}><span>{label}</span>{problem===i?<Minus size={18}/>:<Plus size={18}/>}</Button>)}</div>{problem!==null&&<div className="suggestion" aria-live="polite"><span className="eyebrow">Here’s what we might explore.</span><div className="solution-parts">{problems[problem][1].map(x=><span key={x}>{x}</span>)}</div><p>A starting point for a conversation. Your business will shape the solution.</p><QuoteLink>Let’s talk about it</QuoteLink></div>}</div></section>
 <section className="quote-section section-pad" id="quote"><div><Chapter n="10">Make room for better</Chapter><h2>Let’s build<br/>something<br/>that <em>works.</em></h2><p>For your business. For your customers.<br/>And for the time you’d like back.</p><p className="quote-support">Tell us what’s taking up your time, where opportunities are slipping through, or what you’d like your business to do better.<br/><br/>We’ll help figure out what makes sense.</p></div><QuoteForm selected={problem===null?'':problems[problem][0]}/></section>
 <section className="departure-scene"><img src="/images/ending.webp" srcSet="/images/ending-small.webp 800w, /images/ending.webp 1600w" sizes="100vw" width="1536" height="1024" alt="The electrician closes the toolbox at the end of the workday" loading="lazy"/><div><span className="eyebrow">THE END OF THE WORKDAY</span><p>Tools down.<br/>Time to head home.</p></div></section><section className="ending" id="ending"><img src="/images/departure.webp" srcSet="/images/departure-small.webp 800w, /images/departure.webp 1600w" sizes="(max-width: 767px) 100vw, 100vw" alt="The electrician drives home in the white van while the workshop systems keep working" width="1536" height="1024" loading="lazy"/><div className="ending-overlay"/><div className="ending-copy"><Chapter n="11">Call it a day</Chapter><h2>Less busywork.<br/><em>More business.</em></h2><p>You can switch off.<br/>The right systems keep things moving.</p><QuoteLink light/></div><div className="background-work">{['New enquiry','Lead captured','Follow-up sent','CRM updated'].map(x=><span key={x}><Check size={13}/>{x}</span>)}</div></section>
 </main><footer className="footer section-pad"><div className="footer-top"><div><a href="#start" className="wordmark"><span className="brand-symbol">s.</span>SQUIRREL LABS</a><p>AI · AUTOMATION · WEB<br/>Built for business. Australia-wide.</p></div><div><span>Services</span>{services.map((s,i)=><button key={s.id} onClick={()=>setService(i)}>{['AI agents','Automation','Websites','CRM & integrations'][i]}</button>)}</div><div><span>Company</span><button onClick={()=>setLegal('about')}>About</button><a href="#experiments">Inside the lab</a><a href="#quote">Contact</a></div><div><span>The small print</span><button onClick={()=>setLegal('privacy')}>Privacy</button><button onClick={()=>setLegal('terms')}>Terms</button></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Squirrel Labs</span><span>A Purple Squirrel Company</span><a href="#start">Back to the beginning ↑</a></div></footer>
 <Dialog open={service!==null} onOpenChange={open=>{if(!open)setService(null);}}><DialogContent className="detail-dialog">{service!==null&&<><span className="eyebrow">{services[service].name}</span><DialogTitle>{services[service].title}</DialogTitle><DialogDescription>{services[service].copy}</DialogDescription><ul className="detail-list">{services[service].detail.map(x=><li key={x}><Check size={17}/>{x}</li>)}</ul><p className="detail-outcome">{services[service].outcome}</p><a className="action" href="#quote" onClick={()=>setService(null)}>Get a quote<ArrowUpRight size={18}/></a></>}</DialogContent></Dialog>
 <Dialog open={experiment!==null} onOpenChange={open=>{if(!open)setExperiment(null);}}><DialogContent className="detail-dialog prototype-dialog">{experiment!==null&&<><span className="eyebrow">EXP. 00{experiment+1} / INTERACTIVE PROTOTYPE</span><DialogTitle>{experiments[experiment]}</DialogTitle><DialogDescription>{['Turn a website enquiry into a useful handover.','See how a quote can be followed up without another sticky note.','Keep an enquiry moving from first contact to a booked job.','Give a website visitor a clear next step.','Keep customers informed after the job.','Move a qualified enquiry into an organised pipeline.'][experiment]}</DialogDescription><div className="demo-surface">{demoStage===0?<><label>Customer name<Input value={demoName} onChange={e=>setDemoName(e.target.value)} maxLength={50}/></label><label>What do they need?<Input value={demoService} onChange={e=>setDemoService(e.target.value)} maxLength={100}/></label><Button className="action" disabled={!demoName.trim()||!demoService.trim()} onClick={()=>setDemoStage(1)}><Play size={15}/>Run the experiment</Button></>:<><div className="demo-event"><Check/>{['Enquiry captured','Quote follow-up prepared','Lead added to your pipeline','Website enquiry created','Customer update prepared','Qualified lead moved'][experiment]}</div><p><strong>{demoName}</strong> · {demoService}</p><ol className="demo-log"><li>Customer details captured</li><li>{['Service and location questions prepared','Follow-up scheduled for two business days later','Assigned status: Ready for callback','Enquiry routed to the business workflow','Thank-you message queued after job completion','Pipeline updated: New → Qualified'][experiment]}</li><li>One useful handover for the business owner</li></ol><Button variant="outline" onClick={()=>setDemoStage(0)}>Reset experiment</Button></>}</div><p className="demo-disclosure">Browser simulation using your sample inputs. No AI request, email or CRM update is sent. A production system would connect your website, agent, CRM and automation service.</p><p><strong>What this demonstrates:</strong> a repeatable route from customer information to a clear next action.</p></>}</DialogContent></Dialog>
 <Dialog open={legal!==null} onOpenChange={open=>{if(!open)setLegal(null);}}><DialogContent className="detail-dialog"><DialogTitle>{legal==='about'?'A practical kind of curious.':legal==='privacy'?'Privacy':'Website terms'}</DialogTitle><DialogDescription>{legal==='about'?'Squirrel Labs builds AI agents, automations, websites and connected systems for Australian businesses. Our starting point is the work you want to make easier.':legal==='privacy'?'Your enquiry information is used to understand your needs and respond to your request.':'This website explains our services and shows illustrative prototypes.'}</DialogDescription>{legal==='privacy'?<div className="legal-copy"><p>The quote form collects the contact and business information you provide, along with your project requirements. Submitted requests are stored in the website’s database. Please do not include sensitive personal information.</p><p>We do not sell enquiry information. No advertising trackers are included in this site. The hosting provider may process technical request information to operate and protect the website.</p><p>Use the contact form to request access to, correction of or deletion of your enquiry information. Contact details and a full business privacy policy will be confirmed before public launch.</p></div>:legal==='terms'?<div className="legal-copy"><p>Examples, timings and prototype outcomes are illustrative and are not guarantees of business results. Prototype interactions do not send real customer messages or update external systems.</p><p>Submitting a quote request does not create a service agreement. Scope, pricing, delivery and any service terms are agreed separately before work begins.</p><p>Business-specific legal terms will be confirmed before public launch.</p></div>:<p>Less busywork. More business.<br/><br/>Australia-wide.</p>}</DialogContent></Dialog>
 </div>;
}
function QuoteForm({selected}:{selected:string}){
 const [step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState('');const [fields,setFields]=useState({name:'',business:'',email:'',phone:'',industry:'',help:'',problem:'',improvement:'',budget:'',timeframe:'',website:''});const id=useRef('');const formRef=useRef<HTMLFormElement>(null);const formHeading=useRef<HTMLHeadingElement>(null);const previousStep=useRef(step);
 useEffect(()=>{if(previousStep.current===step)return;previousStep.current=step;formHeading.current?.focus({preventScroll:true});formRef.current?.scrollIntoView({block:'start',behavior:'instant'});},[step]);
 useEffect(()=>{if(selected)setFields(f=>({...f,help:selected}));},[selected]);const update=(key:keyof typeof fields,value:string)=>setFields(f=>({...f,[key]:value}));
 const field=(key:keyof typeof fields,label:string,type='text',required=true)=><label key={key}>{label}<Input type={type} inputMode={type==='tel'?'tel':type==='email'?'email':undefined} name={key} value={fields[key]} onChange={e=>update(key,e.target.value)} required={required} maxLength={key==='email'?254:160} autoComplete={key==='name'?'name':key==='email'?'email':key==='phone'?'tel':key==='business'?'organization':'off'}/></label>;
 const area=(key:keyof typeof fields,label:string)=><label>{label}<Textarea name={key} value={fields[key]} onChange={e=>update(key,e.target.value)} required maxLength={2500} rows={3}/></label>;
 async function submit(e:FormEvent){e.preventDefault();setError('');if(step<2){setStep(step+1);return;}setBusy(true);id.current ||= crypto.randomUUID();try{const res=await fetch('/api/quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,id:id.current})});const data=await res.json() as {error?:string;reference:string};if(!res.ok)throw new Error(data.error||'We couldn’t save your request. Please try again.');setReceipt(data.reference);}catch(e){setError(e instanceof Error?e.message:'Connection interrupted. Your answers are still here. Please try again.');}finally{setBusy(false);}}
 if(receipt)return <div className="quote-form quote-success" role="status"><span className="success-check"><Check size={28}/></span><h3>Your request is saved.</h3><p>Thanks, {fields.name}. Your project brief has been received.</p><p className="receipt">Reference {receipt}</p><p>We’ll use the details you supplied to understand what could work better.</p></div>;
 return <form ref={formRef} className="quote-form" onSubmit={submit}><div className="form-progress"><span>LET’S START A CONVERSATION</span><span>0{step+1} / 03</span></div><div className="progress-track" role="progressbar" aria-label="Quote form progress" aria-valuenow={step+1} aria-valuemin={1} aria-valuemax={3}><span style={{width:`${(step+1)/3*100}%`}}/></div><h3 ref={formHeading} tabIndex={-1}>{['First, a little about you.','What could work better?','Anything else we should know?'][step]}</h3><div className="form-fields">{step===0?<>{field('name','Your name')}{field('business','Business name')}{field('email','Email address','email')}{field('phone','Phone number','tel')}{field('industry','Your industry')}</>:step===1?<>{area('help','What do you need help with?')}{area('problem','What’s causing the problem today?')}{area('improvement','What would you like to improve?')}</>:<>{field('budget','Budget range (optional)','text',false)}{field('timeframe','Timeframe (optional)','text',false)}<div className="form-review"><span>YOUR REQUEST</span><strong>{fields.business}</strong><p>{fields.help}</p><small>Reply to {fields.email}</small></div><p className="form-privacy">Your details are used to respond to this request. Please don’t include sensitive information. There’s no commitment to proceed.</p></>}</div><label className="honeypot" aria-hidden="true">Leave blank<Input tabIndex={-1} autoComplete="off" value={fields.website} onChange={e=>update('website',e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions">{step>0?<Button variant="ghost" type="button" onClick={()=>setStep(step-1)} disabled={busy}><ChevronLeft size={15}/>Back</Button>:<small>No jargon. No obligation.</small>}<Button type="submit" className="action" disabled={busy}>{busy?'Sending…':step===2?'Get a quote':'Continue'}<ArrowRight size={17}/></Button></div></form>;
}






